//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoAtkIntervalComponent
{
    
    public static void AddAtkIntervalComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.AtkIntervalComponent);
    }
    
    public static void AddAtkIntervalComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.AtkIntervalComponent)ecsEntity.AddComponent(Components.AtkIntervalComponent);
        p.Time = param;
    }
          
    public static GXGame.AtkIntervalComponent GetAtkIntervalComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.AtkIntervalComponent)ecsEntity.GetComponent(Components.AtkIntervalComponent);
    }
     
    public static ECSEntity SetAtkIntervalComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.AtkIntervalComponent)ecsEntity.GetComponent(Components.AtkIntervalComponent);
        p.Time = param;
        ((World)ecsEntity.Parent).Reactive(Components.AtkIntervalComponent, ecsEntity);
        
        return ecsEntity;
    }
         
}