//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoBeingCaughtComponent
{
    
    public static void AddBeingCaughtComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.BeingCaughtComponent);
    }
    
    public static void AddBeingCaughtComponent(this ECSEntity ecsEntity,GXGame.BeingCaughtData param)
    {
        var p  =  (GXGame.BeingCaughtComponent)ecsEntity.AddComponent(Components.BeingCaughtComponent);
        p.Value = param;
    }
          
    public static GXGame.BeingCaughtComponent GetBeingCaughtComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.BeingCaughtComponent)ecsEntity.GetComponent(Components.BeingCaughtComponent);
    }
     
    public static ECSEntity SetBeingCaughtComponent(this ECSEntity ecsEntity,GXGame.BeingCaughtData param)
    {
        var p = (GXGame.BeingCaughtComponent)ecsEntity.GetComponent(Components.BeingCaughtComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BeingCaughtComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetBeingCaughtComponent(this ECSEntity ecsEntity,GXGame.BeingCaughtData param)
    {
        var p = (GXGame.BeingCaughtComponent)ecsEntity.GetComponent(Components.BeingCaughtComponent);
        if(p==null)
        {
           p = (GXGame.BeingCaughtComponent)(ecsEntity.AddComponent(Components.BeingCaughtComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BeingCaughtComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}