//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoBoxColliderComponent
{
    
    public static void AddBoxColliderComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.BoxColliderComponent);
    }
    
    public static void AddBoxColliderComponent(this ECSEntity ecsEntity,GXGame.BoxColliderData param)
    {
        var p  =  (GXGame.BoxColliderComponent)ecsEntity.AddComponent(Components.BoxColliderComponent);
        p.Value = param;
    }
          
    public static GXGame.BoxColliderComponent GetBoxColliderComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.BoxColliderComponent)ecsEntity.GetComponent(Components.BoxColliderComponent);
    }
     
    public static ECSEntity SetBoxColliderComponent(this ECSEntity ecsEntity,GXGame.BoxColliderData param)
    {
        var p = (GXGame.BoxColliderComponent)ecsEntity.GetComponent(Components.BoxColliderComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BoxColliderComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetBoxColliderComponent(this ECSEntity ecsEntity,GXGame.BoxColliderData param)
    {
        var p = (GXGame.BoxColliderComponent)ecsEntity.GetComponent(Components.BoxColliderComponent);
        if(p==null)
        {
           p = (GXGame.BoxColliderComponent)(ecsEntity.AddComponent(Components.BoxColliderComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BoxColliderComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}