//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoBoxCollider
{
    
    public static void AddBoxCollider(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.BoxCollider);
    }
    
    public static void AddBoxCollider(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p  =  (GXGame.BoxCollider)ecsEntity.AddComponent(Components.BoxCollider);
        p.Value = param;
    }
          
    public static GXGame.BoxCollider GetBoxCollider(this ECSEntity ecsEntity)
    {
        return (GXGame.BoxCollider)ecsEntity.GetComponent(Components.BoxCollider);
    }
     
    public static ECSEntity SetBoxCollider(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p = (GXGame.BoxCollider)ecsEntity.GetComponent(Components.BoxCollider);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BoxCollider, ecsEntity);
        
        return ecsEntity;
    }
         
}