//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoCameraComponent
{
    
    public static void AddCameraComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CameraComponent);
    }
          
    public static GXGame.CameraComponent GetCameraComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.CameraComponent)ecsEntity.GetComponent(Components.CameraComponent);
    }
         
}