//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoCapsuleCollider
{
    
    public static void AddCapsuleCollider(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CapsuleCollider);
    }
    
    public static void AddCapsuleCollider(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p  =  (GXGame.CapsuleCollider)ecsEntity.AddComponent(Components.CapsuleCollider);
        p.Value = param;
    }
          
    public static GXGame.CapsuleCollider GetCapsuleCollider(this ECSEntity ecsEntity)
    {
        return (GXGame.CapsuleCollider)ecsEntity.GetComponent(Components.CapsuleCollider);
    }
     
    public static ECSEntity SetCapsuleCollider(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p = (GXGame.CapsuleCollider)ecsEntity.GetComponent(Components.CapsuleCollider);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CapsuleCollider, ecsEntity);
        
        return ecsEntity;
    }
         
}