//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoCapsuleColliderComponent
{
    
    public static void AddCapsuleColliderComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CapsuleColliderComponent);
    }
    
    public static void AddCapsuleColliderComponent(this ECSEntity ecsEntity,GXGame.CapsuleColliderData param)
    {
        var p  =  (GXGame.CapsuleColliderComponent)ecsEntity.AddComponent(Components.CapsuleColliderComponent);
        p.Value = param;
    }
          
    public static GXGame.CapsuleColliderComponent GetCapsuleColliderComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.CapsuleColliderComponent)ecsEntity.GetComponent(Components.CapsuleColliderComponent);
    }
     
    public static ECSEntity SetCapsuleColliderComponent(this ECSEntity ecsEntity,GXGame.CapsuleColliderData param)
    {
        var p = (GXGame.CapsuleColliderComponent)ecsEntity.GetComponent(Components.CapsuleColliderComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CapsuleColliderComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetCapsuleColliderComponent(this ECSEntity ecsEntity,GXGame.CapsuleColliderData param)
    {
        var p = (GXGame.CapsuleColliderComponent)ecsEntity.GetComponent(Components.CapsuleColliderComponent);
        if(p==null)
        {
           p = (GXGame.CapsuleColliderComponent)(ecsEntity.AddComponent(Components.CapsuleColliderComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CapsuleColliderComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}