//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoCaughtComponent
{
    
    public static void AddCaughtComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CaughtComponent);
    }
    
    public static void AddCaughtComponent(this ECSEntity ecsEntity,GameFrame.ECSEntity param)
    {
        var p  =  (GXGame.CaughtComponent)ecsEntity.AddComponent(Components.CaughtComponent);
        p.Value = param;
    }
          
    public static GXGame.CaughtComponent GetCaughtComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.CaughtComponent)ecsEntity.GetComponent(Components.CaughtComponent);
    }
     
    public static ECSEntity SetCaughtComponent(this ECSEntity ecsEntity,GameFrame.ECSEntity param)
    {
        var p = (GXGame.CaughtComponent)ecsEntity.GetComponent(Components.CaughtComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CaughtComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetCaughtComponent(this ECSEntity ecsEntity,GameFrame.ECSEntity param)
    {
        var p = (GXGame.CaughtComponent)ecsEntity.GetComponent(Components.CaughtComponent);
        if(p==null)
        {
           p = (GXGame.CaughtComponent)(ecsEntity.AddComponent(Components.CaughtComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CaughtComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}