//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoCollisionGroundType
{
    
    public static void AddCollisionGroundType(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CollisionGroundType);
    }
    
    public static void AddCollisionGroundType(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p  =  (GXGame.CollisionGroundType)ecsEntity.AddComponent(Components.CollisionGroundType);
        p.Type = param;
    }
          
    public static GXGame.CollisionGroundType GetCollisionGroundType(this ECSEntity ecsEntity)
    {
        return (GXGame.CollisionGroundType)ecsEntity.GetComponent(Components.CollisionGroundType);
    }
     
    public static ECSEntity SetCollisionGroundType(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p = (GXGame.CollisionGroundType)ecsEntity.GetComponent(Components.CollisionGroundType);
        p.Type = param;
        ((World)ecsEntity.Parent).Reactive(Components.CollisionGroundType, ecsEntity);
        
        return ecsEntity;
    }
         
}