//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
public static class Components {
    
    public const int Destroy= 0;
    public const int View= 1;
    public const int PlayAtk= 2;
    public const int PreSkillComponent= 3;
    public const int LateSkillComponent= 4;
    public const int AtkIntervalComponent= 5;
    public const int SkillComponent= 6;
    public const int AbilityUnitTypeComponent= 7;
    public const int Player= 8;
    public const int CameraComponent= 9;
    public const int HP= 10;
    public const int WorldPos= 11;
    public const int WorldRotate= 12;
    public const int LocalPos= 13;
    public const int LocalRotate= 14;
    public const int LocalScale= 15;
    public const int Gravity= 16;
    public const int ViewCull= 17;
    public const int AssetPath= 18;
    public const int DestroyCountdown= 19;
    public const int DirectionSpeed= 20;
    public const int MeshRendererColor= 21;
    public const int UseShareMaterial= 22;
    public const int FaceDirection= 23;
    public const int GXInput= 24;
    public const int MoveDirection= 25;
    public const int MoveSpeed= 26;
    public const int TargetPos= 27;
    public const int ViewType= 28;
    public const int YAxisASpeed= 29;
    public const int Monster= 30;
    public const int CampComponent= 31;
    public const int UnitTypeComponent= 32;
    public const int BehaviorTreeComponent= 33;
    public const int CapsuleCollider= 34;
    public const int YAxisAcceleration= 35;
    public const int RaycastHitMsg= 36;
    public const int CollisionGroundType= 37;
    public const int GroundMsgComponent= 38;
    
    public const int TotalComponents = 39;
    
    
    public static readonly System.Type[] ComponentTypes = {
        
        typeof(GameFrame.Destroy),
        typeof(GameFrame.View),
        typeof(GXGame.PlayAtk),
        typeof(GXGame.PreSkillComponent),
        typeof(GXGame.LateSkillComponent),
        typeof(GXGame.AtkIntervalComponent),
        typeof(GXGame.SkillComponent),
        typeof(GXGame.AbilityUnitTypeComponent),
        typeof(GXGame.Player),
        typeof(GXGame.CameraComponent),
        typeof(GXGame.HP),
        typeof(GXGame.WorldPos),
        typeof(GXGame.WorldRotate),
        typeof(GXGame.LocalPos),
        typeof(GXGame.LocalRotate),
        typeof(GXGame.LocalScale),
        typeof(GXGame.Gravity),
        typeof(GXGame.ViewCull),
        typeof(GXGame.AssetPath),
        typeof(GXGame.DestroyCountdown),
        typeof(GXGame.DirectionSpeed),
        typeof(GXGame.MeshRendererColor),
        typeof(GXGame.UseShareMaterial),
        typeof(GXGame.FaceDirection),
        typeof(GXGame.GXInput),
        typeof(GXGame.MoveDirection),
        typeof(GXGame.MoveSpeed),
        typeof(GXGame.TargetPos),
        typeof(GXGame.ViewType),
        typeof(GXGame.YAxisASpeed),
        typeof(GXGame.Monster),
        typeof(GXGame.CampComponent),
        typeof(GXGame.UnitTypeComponent),
        typeof(GXGame.BehaviorTreeComponent),
        typeof(GXGame.CapsuleCollider),
        typeof(GXGame.YAxisAcceleration),
        typeof(GXGame.RaycastHitMsg),
        typeof(GXGame.CollisionGroundType),
        typeof(GXGame.GroundMsgComponent),
    };

    
    public static void SetComponent()
    {
       GXComponents.ComponentTypes = ComponentTypes;   
    }
}
