//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
public static class Components {
    
    public const int Destroy= 0;
    public const int View= 1;
    public const int PlayAtk= 2;
    public const int PreSkillComponent= 3;
    public const int LateSkillComponent= 4;
    public const int AtkIntervalComponent= 5;
    public const int SkillComponent= 6;
    public const int Player= 7;
    public const int CameraComponent= 8;
    public const int HP= 9;
    public const int WorldPos= 10;
    public const int WorldRotate= 11;
    public const int LocalPos= 12;
    public const int LocalRotate= 13;
    public const int LocalScale= 14;
    public const int ViewCull= 15;
    public const int AssetPath= 16;
    public const int DestroyCountdown= 17;
    public const int DirectionSpeed= 18;
    public const int MeshRendererColor= 19;
    public const int UseShareMaterial= 20;
    public const int FaceDirection= 21;
    public const int GXInput= 22;
    public const int MoveDirection= 23;
    public const int MoveSpeed= 24;
    public const int PathFindingTargetPos= 25;
    public const int ViewType= 26;
    public const int YAxisASpeed= 27;
    public const int Monster= 28;
    public const int CampComponent= 29;
    public const int UnitTypeComponent= 30;
    public const int BehaviorTreeComponent= 31;
    public const int CapsuleCollider= 32;
    public const int BoxCollider= 33;
    public const int YAxisAcceleration= 34;
    public const int RaycastHitMsg= 35;
    public const int CollisionGroundType= 36;
    public const int FeedBackBoxComponent= 37;
    public const int GridDataComponent= 38;
    public const int FindPathComponent= 39;
    public const int GroundMsgComponent= 40;
    public const int CollisionMsgComponent= 41;
    public const int GravityComponent= 42;
    public const int OperationComponent= 43;
    public const int RovAgent= 44;
    
    public const int TotalComponents = 45;
    
    
    public static readonly System.Type[] ComponentTypes = {
        
        typeof(GameFrame.Destroy),
        typeof(GameFrame.View),
        typeof(GXGame.PlayAtk),
        typeof(GXGame.PreSkillComponent),
        typeof(GXGame.LateSkillComponent),
        typeof(GXGame.AtkIntervalComponent),
        typeof(GXGame.SkillComponent),
        typeof(GXGame.Player),
        typeof(GXGame.CameraComponent),
        typeof(GXGame.HP),
        typeof(GXGame.WorldPos),
        typeof(GXGame.WorldRotate),
        typeof(GXGame.LocalPos),
        typeof(GXGame.LocalRotate),
        typeof(GXGame.LocalScale),
        typeof(GXGame.ViewCull),
        typeof(GXGame.AssetPath),
        typeof(GXGame.DestroyCountdown),
        typeof(GXGame.DirectionSpeed),
        typeof(GXGame.MeshRendererColor),
        typeof(GXGame.UseShareMaterial),
        typeof(GXGame.FaceDirection),
        typeof(GXGame.GXInput),
        typeof(GXGame.MoveDirection),
        typeof(GXGame.MoveSpeed),
        typeof(GXGame.PathFindingTargetPos),
        typeof(GXGame.ViewType),
        typeof(GXGame.YAxisASpeed),
        typeof(GXGame.Monster),
        typeof(GXGame.CampComponent),
        typeof(GXGame.UnitTypeComponent),
        typeof(GXGame.BehaviorTreeComponent),
        typeof(GXGame.CapsuleCollider),
        typeof(GXGame.BoxCollider),
        typeof(GXGame.YAxisAcceleration),
        typeof(GXGame.RaycastHitMsg),
        typeof(GXGame.CollisionGroundType),
        typeof(GXGame.FeedBackBoxComponent),
        typeof(GXGame.GridDataComponent),
        typeof(GXGame.FindPathComponent),
        typeof(GXGame.PreviousGroundMsgComponent),
        typeof(GXGame.CollisionMsgComponent),
        typeof(GXGame.GravityComponent),
        typeof(GXGame.OperationComponent),
        typeof(GXGame.Scripts.Runtime.RovAgent),
    };

    
    public static void SetComponent()
    {
       GXComponents.ComponentTypes = ComponentTypes;   
    }
}
