//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoFaceDirection
{
    
    public static void AddFaceDirection(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.FaceDirection);
    }
    
    public static void AddFaceDirection(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.FaceDirection)ecsEntity.AddComponent(Components.FaceDirection);
        p.Value = param;
    }
          
    public static GXGame.FaceDirection GetFaceDirection(this ECSEntity ecsEntity)
    {
        return (GXGame.FaceDirection)ecsEntity.GetComponent(Components.FaceDirection);
    }
     
    public static ECSEntity SetFaceDirection(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.FaceDirection)ecsEntity.GetComponent(Components.FaceDirection);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.FaceDirection, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}