//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoFallingSpeedComponent
{
    
    public static void AddFallingSpeedComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.FallingSpeedComponent);
    }
    
    public static void AddFallingSpeedComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.FallingSpeedComponent)ecsEntity.AddComponent(Components.FallingSpeedComponent);
        p.Value = param;
    }
          
    public static GXGame.FallingSpeedComponent GetFallingSpeedComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.FallingSpeedComponent)ecsEntity.GetComponent(Components.FallingSpeedComponent);
    }
     
    public static ECSEntity SetFallingSpeedComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.FallingSpeedComponent)ecsEntity.GetComponent(Components.FallingSpeedComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.FallingSpeedComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetFallingSpeedComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.FallingSpeedComponent)ecsEntity.GetComponent(Components.FallingSpeedComponent);
        if(p==null)
        {
           p = (GXGame.FallingSpeedComponent)(ecsEntity.AddComponent(Components.FallingSpeedComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.FallingSpeedComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}