//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoForceWorldRotate
{
    
    public static void AddForceWorldRotate(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.ForceWorldRotate);
    }
    
    public static void AddForceWorldRotate(this ECSEntity ecsEntity,UnityEngine.Quaternion param)
    {
        var p  =  (GXGame.ForceWorldRotate)ecsEntity.AddComponent(Components.ForceWorldRotate);
        p.Value = param;
    }
          
    public static GXGame.ForceWorldRotate GetForceWorldRotate(this ECSEntity ecsEntity)
    {
        return (GXGame.ForceWorldRotate)ecsEntity.GetComponent(Components.ForceWorldRotate);
    }
     
    public static ECSEntity SetForceWorldRotate(this ECSEntity ecsEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.ForceWorldRotate)ecsEntity.GetComponent(Components.ForceWorldRotate);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.ForceWorldRotate, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetForceWorldRotate(this ECSEntity ecsEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.ForceWorldRotate)ecsEntity.GetComponent(Components.ForceWorldRotate);
        if(p==null)
        {
           p = (GXGame.ForceWorldRotate)(ecsEntity.AddComponent(Components.ForceWorldRotate));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.ForceWorldRotate, ecsEntity);
        
        return ecsEntity;
    } 
         
}