//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoForceWorldPos
{
    
    public static void AddForceWorldPos(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.ForceWorldPos);
    }
    
    public static void AddForceWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.ForceWorldPos)ecsEntity.AddComponent(Components.ForceWorldPos);
        p.Value = param;
    }
          
    public static GXGame.ForceWorldPos GetForceWorldPos(this ECSEntity ecsEntity)
    {
        return (GXGame.ForceWorldPos)ecsEntity.GetComponent(Components.ForceWorldPos);
    }
     
    public static ECSEntity SetForceWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.ForceWorldPos)ecsEntity.GetComponent(Components.ForceWorldPos);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.ForceWorldPos, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetForceWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.ForceWorldPos)ecsEntity.GetComponent(Components.ForceWorldPos);
        if(p==null)
        {
           p = (GXGame.ForceWorldPos)(ecsEntity.AddComponent(Components.ForceWorldPos));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.ForceWorldPos, ecsEntity);
        
        return ecsEntity;
    } 
         
}