//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoGravityDirComponent
{
    
    public static void AddGravityDirComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.GravityDirComponent);
    }
    
    public static void AddGravityDirComponent(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.GravityDirComponent)ecsEntity.AddComponent(Components.GravityDirComponent);
        p.Value = param;
    }
          
    public static GXGame.GravityDirComponent GetGravityDirComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.GravityDirComponent)ecsEntity.GetComponent(Components.GravityDirComponent);
    }
     
    public static ECSEntity SetGravityDirComponent(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.GravityDirComponent)ecsEntity.GetComponent(Components.GravityDirComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GravityDirComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetGravityDirComponent(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.GravityDirComponent)ecsEntity.GetComponent(Components.GravityDirComponent);
        if(p==null)
        {
           p = (GXGame.GravityDirComponent)(ecsEntity.AddComponent(Components.GravityDirComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GravityDirComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}