//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoGravity
{
    
    public static void AddGravity(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.Gravity);
    }
    
    public static void AddGravity(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.Gravity)ecsEntity.AddComponent(Components.Gravity);
        p.Value = param;
    }
          
    public static GXGame.Gravity GetGravity(this ECSEntity ecsEntity)
    {
        return (GXGame.Gravity)ecsEntity.GetComponent(Components.Gravity);
    }
     
    public static ECSEntity SetGravity(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.Gravity)ecsEntity.GetComponent(Components.Gravity);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.Gravity, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}