//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoGravityComponent
{
    
    public static void AddGravityComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.GravityComponent);
    }
    
    public static void AddGravityComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.GravityComponent)ecsEntity.AddComponent(Components.GravityComponent);
        p.Value = param;
    }
          
    public static GXGame.GravityComponent GetGravityComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.GravityComponent)ecsEntity.GetComponent(Components.GravityComponent);
    }
     
    public static ECSEntity SetGravityComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.GravityComponent)ecsEntity.GetComponent(Components.GravityComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GravityComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetGravityComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.GravityComponent)ecsEntity.GetComponent(Components.GravityComponent);
        if(p==null)
        {
           p = (GXGame.GravityComponent)(ecsEntity.AddComponent(Components.GravityComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GravityComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}