//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoGroundCollisionComponent
{
    
    public static void AddGroundCollisionComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.GroundCollisionComponent);
    }
    
    public static void AddGroundCollisionComponent(this ECSEntity ecsEntity,GXGame.GroundCollision param)
    {
        var p  =  (GXGame.GroundCollisionComponent)ecsEntity.AddComponent(Components.GroundCollisionComponent);
        p.Value = param;
    }
          
    public static GXGame.GroundCollisionComponent GetGroundCollisionComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.GroundCollisionComponent)ecsEntity.GetComponent(Components.GroundCollisionComponent);
    }
     
    public static ECSEntity SetGroundCollisionComponent(this ECSEntity ecsEntity,GXGame.GroundCollision param)
    {
        var p = (GXGame.GroundCollisionComponent)ecsEntity.GetComponent(Components.GroundCollisionComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GroundCollisionComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetGroundCollisionComponent(this ECSEntity ecsEntity,GXGame.GroundCollision param)
    {
        var p = (GXGame.GroundCollisionComponent)ecsEntity.GetComponent(Components.GroundCollisionComponent);
        if(p==null)
        {
           p = (GXGame.GroundCollisionComponent)(ecsEntity.AddComponent(Components.GroundCollisionComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GroundCollisionComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}