//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoGroundMsgComponent
{
    
    public static void AddGroundMsgComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.GroundMsgComponent);
    }
    
    public static void AddGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p  =  (GXGame.PreviousGroundMsgComponent)ecsEntity.AddComponent(Components.GroundMsgComponent);
        p.Value = param;
    }
          
    public static GXGame.PreviousGroundMsgComponent GetGroundMsgComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.GroundMsgComponent);
    }
     
    public static ECSEntity SetGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p = (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.GroundMsgComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GroundMsgComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p = (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.GroundMsgComponent);
        if(p==null)
        {
           p = (GXGame.PreviousGroundMsgComponent)(ecsEntity.AddComponent(Components.GroundMsgComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.GroundMsgComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}