//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoGXInput
{
    
    public static void AddGXInput(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.GXInput);
    }
          
    public static GXGame.GXInput GetGXInput(this ECSEntity ecsEntity)
    {
        return (GXGame.GXInput)ecsEntity.GetComponent(Components.GXInput);
    }
         
}