//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoJumpSpeed
{
    
    public static void AddJumpSpeed(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.JumpSpeed);
    }
    
    public static void AddJumpSpeed(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.JumpSpeed)ecsEntity.AddComponent(Components.JumpSpeed);
        p.Value = param;
    }
          
    public static GXGame.JumpSpeed GetJumpSpeed(this ECSEntity ecsEntity)
    {
        return (GXGame.JumpSpeed)ecsEntity.GetComponent(Components.JumpSpeed);
    }
     
    public static ECSEntity SetJumpSpeed(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.JumpSpeed)ecsEntity.GetComponent(Components.JumpSpeed);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.JumpSpeed, ecsEntity);
        
        return ecsEntity;
    }
         
}