//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoLateSkillComponent
{
    
    public static void AddLateSkillComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.LateSkillComponent);
    }
    
    public static void AddLateSkillComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.LateSkillComponent)ecsEntity.AddComponent(Components.LateSkillComponent);
        p.Time = param;
    }
          
    public static GXGame.LateSkillComponent GetLateSkillComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.LateSkillComponent)ecsEntity.GetComponent(Components.LateSkillComponent);
    }
     
    public static ECSEntity SetLateSkillComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.LateSkillComponent)ecsEntity.GetComponent(Components.LateSkillComponent);
        p.Time = param;
        ((World)ecsEntity.Parent).Reactive(Components.LateSkillComponent, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}