//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoMonster
{
    
    public static void AddMonster(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.Monster);
    }
          
    public static GXGame.Monster GetMonster(this ECSEntity ecsEntity)
    {
        return (GXGame.Monster)ecsEntity.GetComponent(Components.Monster);
    }
         
}