//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoPathFindingTargetPos
{
    
    public static void AddPathFindingTargetPos(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.PathFindingTargetPos);
    }
    
    public static void AddPathFindingTargetPos(this ECSEntity ecsEntity,UnityEngine.Vector2Int param)
    {
        var p  =  (GXGame.PathFindingTargetPos)ecsEntity.AddComponent(Components.PathFindingTargetPos);
        p.Value = param;
    }
          
    public static GXGame.PathFindingTargetPos GetPathFindingTargetPos(this ECSEntity ecsEntity)
    {
        return (GXGame.PathFindingTargetPos)ecsEntity.GetComponent(Components.PathFindingTargetPos);
    }
     
    public static ECSEntity SetPathFindingTargetPos(this ECSEntity ecsEntity,UnityEngine.Vector2Int param)
    {
        var p = (GXGame.PathFindingTargetPos)ecsEntity.GetComponent(Components.PathFindingTargetPos);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.PathFindingTargetPos, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetPathFindingTargetPos(this ECSEntity ecsEntity,UnityEngine.Vector2Int param)
    {
        var p = (GXGame.PathFindingTargetPos)ecsEntity.GetComponent(Components.PathFindingTargetPos);
        if(p==null)
        {
           p = (GXGame.PathFindingTargetPos)(ecsEntity.AddComponent(Components.PathFindingTargetPos));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.PathFindingTargetPos, ecsEntity);
        
        return ecsEntity;
    } 
         
}