//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoPlayAtk
{
    
    public static void AddPlayAtk(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.PlayAtk);
    }
    
    public static void AddPlayAtk(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p  =  (GXGame.PlayAtk)ecsEntity.AddComponent(Components.PlayAtk);
        p.Id = param;
    }
          
    public static GXGame.PlayAtk GetPlayAtk(this ECSEntity ecsEntity)
    {
        return (GXGame.PlayAtk)ecsEntity.GetComponent(Components.PlayAtk);
    }
     
    public static ECSEntity SetPlayAtk(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p = (GXGame.PlayAtk)ecsEntity.GetComponent(Components.PlayAtk);
        p.Id = param;
        ((World)ecsEntity.Parent).Reactive(Components.PlayAtk, ecsEntity);
        View view = ecsEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtk) (view.Value)).Atk(p);
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetPlayAtk(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p = (GXGame.PlayAtk)ecsEntity.GetComponent(Components.PlayAtk);
        if(p==null)
        {
           p = (GXGame.PlayAtk)(ecsEntity.AddComponent(Components.PlayAtk));
        }
        p.Id = param;
        ((World)ecsEntity.Parent).Reactive(Components.PlayAtk, ecsEntity);
        View view = ecsEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtk) (view.Value)).Atk(p);
        return ecsEntity;
    } 
         
}