//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoPreviousGroundMsgComponent
{
    
    public static void AddPreviousGroundMsgComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.PreviousGroundMsgComponent);
    }
    
    public static void AddPreviousGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p  =  (GXGame.PreviousGroundMsgComponent)ecsEntity.AddComponent(Components.PreviousGroundMsgComponent);
        p.Value = param;
    }
          
    public static GXGame.PreviousGroundMsgComponent GetPreviousGroundMsgComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.PreviousGroundMsgComponent);
    }
     
    public static ECSEntity SetPreviousGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p = (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.PreviousGroundMsgComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.PreviousGroundMsgComponent, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetPreviousGroundMsgComponent(this ECSEntity ecsEntity,GXGame.PreviousGroundMsg param)
    {
        var p = (GXGame.PreviousGroundMsgComponent)ecsEntity.GetComponent(Components.PreviousGroundMsgComponent);
        if(p==null)
        {
           p = (GXGame.PreviousGroundMsgComponent)(ecsEntity.AddComponent(Components.PreviousGroundMsgComponent));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.PreviousGroundMsgComponent, ecsEntity);
        
        return ecsEntity;
    } 
         
}