//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoRaycastHitMsg
{
    
    public static void AddRaycastHitMsg(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.RaycastHitMsg);
    }
    
    public static void AddRaycastHitMsg(this ECSEntity ecsEntity,System.Collections.Generic.List<UnityEngine.RaycastHit> param)
    {
        var p  =  (GXGame.RaycastHitMsg)ecsEntity.AddComponent(Components.RaycastHitMsg);
        p.Value = param;
    }
          
    public static GXGame.RaycastHitMsg GetRaycastHitMsg(this ECSEntity ecsEntity)
    {
        return (GXGame.RaycastHitMsg)ecsEntity.GetComponent(Components.RaycastHitMsg);
    }
     
    public static ECSEntity SetRaycastHitMsg(this ECSEntity ecsEntity,System.Collections.Generic.List<UnityEngine.RaycastHit> param)
    {
        var p = (GXGame.RaycastHitMsg)ecsEntity.GetComponent(Components.RaycastHitMsg);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.RaycastHitMsg, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetRaycastHitMsg(this ECSEntity ecsEntity,System.Collections.Generic.List<UnityEngine.RaycastHit> param)
    {
        var p = (GXGame.RaycastHitMsg)ecsEntity.GetComponent(Components.RaycastHitMsg);
        if(p==null)
        {
           p = (GXGame.RaycastHitMsg)(ecsEntity.AddComponent(Components.RaycastHitMsg));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.RaycastHitMsg, ecsEntity);
        
        return ecsEntity;
    } 
         
}