//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoRovAgent
{
    
    public static void AddRovAgent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.RovAgent);
    }
    
    public static void AddRovAgent(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p  =  (GXGame.Scripts.Runtime.RovAgent)ecsEntity.AddComponent(Components.RovAgent);
        p.Value = param;
    }
          
    public static GXGame.Scripts.Runtime.RovAgent GetRovAgent(this ECSEntity ecsEntity)
    {
        return (GXGame.Scripts.Runtime.RovAgent)ecsEntity.GetComponent(Components.RovAgent);
    }
     
    public static ECSEntity SetRovAgent(this ECSEntity ecsEntity,System.Int32 param)
    {
        var p = (GXGame.Scripts.Runtime.RovAgent)ecsEntity.GetComponent(Components.RovAgent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.RovAgent, ecsEntity);
        
        return ecsEntity;
    }
         
}