//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoUseShareMaterial
{
    
    public static void AddUseShareMaterial(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.UseShareMaterial);
    }
          
    public static GXGame.UseShareMaterial GetUseShareMaterial(this ECSEntity ecsEntity)
    {
        return (GXGame.UseShareMaterial)ecsEntity.GetComponent(Components.UseShareMaterial);
    }
         
}