//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoViewCull
{
    
    public static void AddViewCull(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.ViewCull);
    }
          
    public static GXGame.ViewCull GetViewCull(this ECSEntity ecsEntity)
    {
        return (GXGame.ViewCull)ecsEntity.GetComponent(Components.ViewCull);
    }
         
}