//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoViewType
{
    
    public static void AddViewType(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.ViewType);
    }
    
    public static void AddViewType(this ECSEntity ecsEntity,System.Type param)
    {
        var p  =  (GXGame.ViewType)ecsEntity.AddComponent(Components.ViewType);
        p.Value = param;
    }
          
    public static GXGame.ViewType GetViewType(this ECSEntity ecsEntity)
    {
        return (GXGame.ViewType)ecsEntity.GetComponent(Components.ViewType);
    }
     
    public static ECSEntity SetViewType(this ECSEntity ecsEntity,System.Type param)
    {
        var p = (GXGame.ViewType)ecsEntity.GetComponent(Components.ViewType);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.ViewType, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}