//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoYAxisASpeed
{
    
    public static void AddYAxisASpeed(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.YAxisASpeed);
    }
    
    public static void AddYAxisASpeed(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.YAxisASpeed)ecsEntity.AddComponent(Components.YAxisASpeed);
        p.Value = param;
    }
          
    public static GXGame.YAxisASpeed GetYAxisASpeed(this ECSEntity ecsEntity)
    {
        return (GXGame.YAxisASpeed)ecsEntity.GetComponent(Components.YAxisASpeed);
    }
     
    public static ECSEntity SetYAxisASpeed(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.YAxisASpeed)ecsEntity.GetComponent(Components.YAxisASpeed);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.YAxisASpeed, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetYAxisASpeed(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.YAxisASpeed)ecsEntity.GetComponent(Components.YAxisASpeed);
        if(p==null)
        {
           p = (GXGame.YAxisASpeed)(ecsEntity.AddComponent(Components.YAxisASpeed));
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.YAxisASpeed, ecsEntity);
        
        return ecsEntity;
    } 
         
}