//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoYAxisAcceleration
{
    
    public static void AddYAxisAcceleration(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.YAxisAcceleration);
    }
    
    public static void AddYAxisAcceleration(this ECSEntity ecsEntity,System.Boolean param)
    {
        var p  =  (GXGame.YAxisAcceleration)ecsEntity.AddComponent(Components.YAxisAcceleration);
        p.Value = param;
    }
          
    public static GXGame.YAxisAcceleration GetYAxisAcceleration(this ECSEntity ecsEntity)
    {
        return (GXGame.YAxisAcceleration)ecsEntity.GetComponent(Components.YAxisAcceleration);
    }
     
    public static ECSEntity SetYAxisAcceleration(this ECSEntity ecsEntity,System.Boolean param)
    {
        var p = (GXGame.YAxisAcceleration)ecsEntity.GetComponent(Components.YAxisAcceleration);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.YAxisAcceleration, ecsEntity);
        
        return ecsEntity;
    }
         
}