//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using FairyGUI;
using GameFrame;
namespace GXGame
{
    public partial class UICardListWindowView : UIViewBase
    {
           
        private GButton _n43;
        public GButton n43 { get { return _n43 ??= (GButton)Root.GetChild("n43"); } }     
        private GButton _n44;
        public GButton n44 { get { return _n44 ??= (GButton)Root.GetChild("n44"); } }     
        private GButton _n45;
        public GButton n45 { get { return _n45 ??= (GButton)Root.GetChild("n45"); } }          
    }
}
