//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;

public static class AutoBindEvent
{
    public static void AddSystem()
    {
        var  eventData =  EventData.Instance;
        
        eventData.AddSourceDic(typeof(GXGame.UICardListWindow),typeof(GXGame.ITestEvent1));
    }
}

