//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoBehaviorTreeComponent
{
    
    public static void AddBehaviorTreeComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.BehaviorTreeComponent);
    }
    
    public static void AddBehaviorTreeComponent(this ECSEntity ecsEntity,System.String param)
    {
        var p  =  (GXGame.BehaviorTreeComponent)ecsEntity.AddComponent(Components.BehaviorTreeComponent);
        p.Value = param;
    }
          
    public static GXGame.BehaviorTreeComponent GetBehaviorTreeComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.BehaviorTreeComponent)ecsEntity.GetComponent(Components.BehaviorTreeComponent);
    }
     
    public static ECSEntity SetBehaviorTreeComponent(this ECSEntity ecsEntity,System.String param)
    {
        var p = (GXGame.BehaviorTreeComponent)ecsEntity.GetComponent(Components.BehaviorTreeComponent);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.BehaviorTreeComponent, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}