//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoCollisionBox
{
    
    public static void AddCollisionBox(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.CollisionBox);
    }
    
    public static void AddCollisionBox(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p  =  (GXGame.CollisionBox)ecsEntity.AddComponent(Components.CollisionBox);
        p.Value = param;
    }
          
    public static GXGame.CollisionBox GetCollisionBox(this ECSEntity ecsEntity)
    {
        return (GXGame.CollisionBox)ecsEntity.GetComponent(Components.CollisionBox);
    }
     
    public static ECSEntity SetCollisionBox(this ECSEntity ecsEntity,Common.Runtime.GXGameObject param)
    {
        var p = (GXGame.CollisionBox)ecsEntity.GetComponent(Components.CollisionBox);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(Components.CollisionBox, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}