//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoPlayer
{
    
    public static void AddPlayer(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.Player);
    }
          
    public static GXGame.Player GetPlayer(this ECSEntity ecsEntity)
    {
        return (GXGame.Player)ecsEntity.GetComponent(Components.Player);
    }
         
}