//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoPreSkillComponent
{
    
    public static void AddPreSkillComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.PreSkillComponent);
    }
    
    public static void AddPreSkillComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p  =  (GXGame.PreSkillComponent)ecsEntity.AddComponent(Components.PreSkillComponent);
        p.Time = param;
    }
          
    public static GXGame.PreSkillComponent GetPreSkillComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.PreSkillComponent)ecsEntity.GetComponent(Components.PreSkillComponent);
    }
     
    public static ECSEntity SetPreSkillComponent(this ECSEntity ecsEntity,System.Single param)
    {
        var p = (GXGame.PreSkillComponent)ecsEntity.GetComponent(Components.PreSkillComponent);
        p.Time = param;
        ((World)ecsEntity.Parent).Reactive(Components.PreSkillComponent, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}